### ISSUE TITLE
更改gitbook的配置信息

### ISSUE THREAD

**Issue by badboy315** [OpenMindClub/OMOOC.py#11]
由于更改了gitbook的账户。第一次push的时候，有提示输入gitbook的用户名和密码。后变更账户，无提示gitbook相关帐号和密码。

查询git config
`tao at taodeAir in ~
[1] $ git config --list                                                       ✘
filter.media.required=true
filter.media.clean=git media clean %f
filter.media.smudge=git media smudge %f
user.name=badboy315
user.email=badboy315@gmail.com
filter.hawser.clean=git hawser clean %f
filter.hawser.smudge=git hawser smudge %f
filter.hawser.required=true`

推送gitbook出现以下提示
`tao at taodeAir in ~/dev/Github/pythoncamp0 on master
[128] $ git push -u gitbook master                                            ✘
fatal: unable to access 'https://git.gitbook.com/gonghejian99/pythoncamp0.git/': The requested URL returned error: 403`

ps: github push完整正常。

**Comment by badboy315** [comment]
目前这个问题依然没有解决。

目前的操作方法是：
进入 gitbook config 进行修改回原来通过 gitbook 验证的GIT.

PUSH恢复正常。

下面出现新问题了

如何在「终端」更改 gitbook 的 ID.

**Comment by badboy315** [comment]
感谢「童遥」在微信给予的帮助。

目前直接删除「新注册」的 gitbook 账户。删除之后，可以 github 绑定和原来 gitbook 账户。

**Comment by balsamleo** [comment]
我也遇到这个坑了,问题在于gitbook与github的用户密码不是同一回事.
提醒输入密码的时候,输入Api Token下面的数字组合.

在 2015年3月18日 上午11:53，badboy315 <notifications@github.com>写道：

**Comment by badboy315** [comment]
+ 如果已经绑定了一个 GITBOOK 的账号， 在使用其他账号的时候， 完全没有输入GITBOOK的密码提示啊。

+ 所以， 后面还是用回原来的绑定的 GITBOOK 账号。
