### ISSUE TITLE
[List]Python二期星球启航，新手村任务包发放中，快！

### ISSUE THREAD

**Issue by cnfeat** [OpenMindClub/OMOOC.py#12]
#[开智学院 | 星际跃迁：像程序一般升级自己](http://mp.weixin.qq.com/s?__biz=MzA4ODM4ODQ3MQ==&mid=207846812&idx=1&sn=5ba1680b5024257b0b9113247444f42e&scene=1&srcid=0909p5SDj2NRONcJURjPymqQ&key=dffc561732c22651ec73b548da0d5e63ca0770552428a9df2c613ca1fce5b5cb6485315edc456bf16233f0daf500f14f&ascene=0&uin=MTgwMjY4MjE0MA%3D%3D&devicetype=iMac+MacBookPro12%2C1+OSX+OSX+10.10.5+build(14F27)&version=11020201&pass_ticket=CMbwTxFp4Bv%2B241P%2BKW%2Fj3XOl1xRblIqlyqDdAhoD2X8eJZILz0IQye1hWodtt2r)

## [挑战邀请函 `Beta`](https://github.com/OpenMindClub/OMOOC.py/issues/12)

恭喜各位小伙伴来到新星系挑战关口前，接下来为大家介绍一下开智 Python 二期（内测）的挑战内容。

挑战内容主要包含在以下任务包中：

- 基础工具使用任务包（10%）
 - [[Task.1]二期（内测）学员签到入口](https://github.com/OpenMindClub/OMOOC.py/issues/13)
- 自主思考记录任务包（40%）
 - [[Task.2]入学三问提交处](https://github.com/OpenMindClub/OMOOC.py/issues/14)
- 自主持续追踪任务包（50%）
 - [[Task.3]持续追踪签到处](https://github.com/OpenMindClub/OMOOC.py/issues/15)
- 社群协作创新任务包（50%）
 - [[Task.4]社群协作创新汇总处](https://github.com/OpenMindClub/OMOOC.py/issues/16)

任务包完成条超过90%，方有机会进入开智学院与 Boss大妈 一起进行愉快好玩的学习。

现在由我来为你介绍各任务包的具体内容：

### 一、基础工具使用任务包（10%）

任务说明：在指定的[issue:[Task.1]](https://github.com/OpenMindClub/OMOOC.py/issues/13)中提交自己的 github 帐号、个人代码仓库和自己常用社交网络 ID，并注明入群时间与提交时间
>- 考验：github 的使用基础；
>- 指标：参考示例，一项 +2%；

### 二、自主思考记录任务包（40%）

任务说明：在指定的[issue:[Task.2]](https://github.com/OpenMindClub/OMOOC.py/issues/14)中用 markdown 格式发表入学三问：

  - 我想知道什么？
	- 我现在的基础如何，为什么想学编程？
	- 我来参与开智学院的编程课程，希望学到什么，希望课程结束之后，自己可以做成怎样的事情？
  - 我期待学到什么？
	- 对于我希望学到的东西，如果自学，可以如何学到？
	- 希望开智课程如何助益自己学到这些东西？
  - 如何证明我学到了什么？
	- 怎样的结果能说明我已经掌握了自己想学的内容？

>考验：markdown的基础使用、表达能力、入学意愿和自主解决问题潜能
>
>指标：
>
>- 文字表达（10%）
 - 字数；插图；是否原创；是否标识引用；是否接近教程
>- 明确具体，可以实现（10%）
>- 成果量化，实现时间（10%）
>- 提交时间（10%）

### 三、自主持续追踪任务包（50%）

任务说明：在指定的[issue:[Task.3]](https://github.com/OpenMindClub/OMOOC.py/issues/15)中提交追踪开智一刻或你自学其他编程有关知识的过程，记录每日学习进展（比如做了什么事情，得到的结果是什么）

>考验：连续记述自学过程的天数和持续做一件事情的态度
>
>指标：
>
>- 总记十次一刻的分享纪要
>- 追踪一次，并做出自己的见解 + 5%
>- 自学内容可适当进度加成，总进度不超 50%

### 四、社群协作创新任务包（50%）

任务说明：在指定的[issue:[Task.4]](https://github.com/OpenMindClub/OMOOC.py/issues/16)提交

- 自己对整个挑战任务的建议和看法
- 采用创新的任务提交形式
- 对比并分析各位小伙伴的发言并给予建议和评价
- 找到小伙伴来评论和增补自己的任务
- 将 github 与其他协作工具作对比，哪个平台更适合来完成这个挑战任务？

>考验：独立思考与创新执行
>
>指标：综合考量
>

### 最后

让我们回到初心：

![](http://7d9mjz.com1.z0.glb.clouddn.com/Py1.jpg)

**Comment by ZoomQuiet** [comment]
俺看到的:

- 为毛不和 [Python二期招生简章（对外） · Issue #14 · OpenMindClub/2.OMOOC.py](https://github.com/OpenMindClub/2.OMOOC.py/issues/14#issuecomment-138904657) 相互链接?
- 为毛对已经失效的 Issue 关闭?
- 为毛没有此文案的发布链接?  [Python二期星球启航，新手村任务包发放中，快！](http://openmind.club/Py2/)
- 为毛没有在对应 整体 pre.2.OMOOC.py 任务规划列表中链接此 Issue?

再再再再再再再再再再再再再再次
提醒: [以 github 为核心的高效协同沟通](https://github.com/OpenMindClub/PRD/issues/1)

当前 开智课程运营 团队的内外知识/信息流径是如何的?! 怎么 [AKA](http://wiki.woodpecker.org.cn/moin/KaoPulity#AKA) 的?!?!?

**Comment by ZoomQuiet** [comment]
已经释放,只有先关闭了

**Comment by ZoomQuiet** [comment]
任务包 
    https://github.com/OpenMindClub/OMOOC.py/wiki/PreTasks2OMOOC
