### ISSUE TITLE
[task]参加开智 Python 入门课是种什么体验?

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC.py#20]
- 时限: 151005 24:00 前提交的为有效作业
- 行动:
    + 从任何渠道挖掘 `开智学院 编程课程` 首届 旗舰班 的所有信息
    + 记录你的挖掘路径以及成果链接
    + 从中选择出最打动你的三点,整理陈述理由
- 指标:
    + 及时性
    + 丰富性
    + 文学性
    + 理解度

**Comment by ZoomQuiet** [comment]
as hide task, closed at first

**Comment by JeremiahZhang** [comment]
Like a Python Star Trek. Go Python with DaMa.

**Comment by ZoomQuiet** [comment]
great! 任务埋下 24 小时以内被 digg 出来了,

mark! 学点+1

@OpenMindClub/py2staff
<https://github.com/orgs/OpenMindClub/teams/py2staff> logging
it!

On Fri, Sep 25, 2015 at 11:15 PM, Leiyu <notifications@github.com> wrote:

> Like a Python Star Trek. Go Python with DaMa.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenMindClub/OMOOC.py/issues/20#issuecomment-143249388>
> .
>



-- 
Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by zoejane** [comment]
## 1. 成为自己想成为的人
我觉得很打动我的一点，是说到成为自己想成为的人。  
可能之前说到学习，说到验收成果，很容易想成是完成一个布置的任务，通过一个什么样的测验，却没有想过自己想要做什么，想成为一个怎样的人。  
不是一直都说要自由的吗？但是当这自由交到手上的时候，又有些迷茫，有些忐忑，有些兴奋。  
我很喜欢这种给人带来无限可能的感觉，好像卸下心中的负担，重新感觉到我又自由了，这种感觉很有趣。  
学着感受自由探索的感觉，一切其实就在并不遥远的地方，伸手就可以触动。  
我喜欢的生活，其实并没有那么遥远。
>参考链接：[什么是“课”](http://wiki.zoomquiet.io/IMHO/om-what-is-ke#_1)

## 2. 用一个新的维度看世界

原来，很多觉得不方便不顺手的事情，懂一点编程，就可以自己去尝试改变；  
原来，看上去好像很cool的编程，真正做起来也没有那么难；  
原来，这件事情还有我以前没有想到的思考维度，不是没有可能，而是之前的我没有看到机会;  
原来，这件事情并没有那么困难，只是我并没有去系统的理清它的脉络...  
我一直觉得在这个时代，互联网+英语，给了我们太多的机会和可能，我能感受到它们的强大力量，但是却不知道如何去使用它们。  
我现在做的事情，只是一种新的尝试，尝试着从一个新的维度去看待这个世界，以及这个世界赋予我们的机会和无限可能。   
我觉得这条路上会有很多不一样的发现。  
>参考链接：[大妈答疑：如何用编程让大脑二次发育？](http://mp.weixin.qq.com/s?__biz=MzA4ODM4ODQ3MQ==&amp;mid=208003243&amp;idx=1&amp;sn=e21264c084e1bc80b3d3b4cbc2526f07&amp;scene=1&amp;srcid=0926Ru0LlHihqJhj0yGajIAe#rd)

## 3.享受编程的快乐

说了太多正儿八经的话，我觉得我都快忘记那种最初的感觉了啦，就是享受编程的快乐。  
还记得最开始接触编程的时候，真的觉得这就是个超酷的玩具，而且所需要的一切东西，居然用一台小小电脑就可以满足。它可以创作出很多很炫很酷的东西，做很多好玩的小玩意。  
是呀，最初的感觉就是，编程很好玩。  
好玩！  
玩性大发，一时兴起，试着去创作一些自己觉得好玩有趣的东西来，做出来自己都觉得超酷超棒，这种感觉很好玩。  
我觉得最该记得的，就是这样一种快乐的感觉。  
尝试的快乐，探索的快乐，创作的快乐，游戏的快乐。
>参考链接：[大妈对编程学习的建议](https://github.com/OpenMindClub/OMOOC.py/wiki/Adviceforcoding_DAMA)

**Comment by ZoomQuiet** [comment]
2015-09-26 23:11 GMT+08:00 Zoe <notifications@github.com>:
>

嗯哼, 目测同时也是写作班的成员, 这一则硬广写的太官方了,
都无法相信是亲历者回顾了, 手工点赞 42!

> 1. 成为自己想成为的人
>
...
> 2. 用一个新的维度看世界
>
....
> 3.享受编程的快乐
>



-- 
Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by zoejane** [comment]
@ZoomQuiet 喵，其实之前就有耳闻还有写作班，我也好有兴趣的说，下次开放的话一定也要报名学一个:)  
居然写出了硬广的感觉，伦家好害羞哇....收到表扬好开心好开心  O(^_^)O  
其实昨天一边看文章一边就觉得有几个点是真的还蛮触动我的，随手写了一些碎片化的想法在印象笔记里。今天看到这个task脑袋里就飘过了之前日记里的一些想法，重新写过一遍后自己看着都觉得挺激励自己的了。

喵，最后我真的要感叹一下用Markdown写出来的东西真的看上去好整洁！我突然觉得我这种每次写东西都像日记散文体的人，行文也有逻辑了...

**Comment by ZoomQuiet** [comment]
> @ZoomQuiet

...

> 喵，最后我真的要感叹一下用Markdown写出来的东西真的看上去好整洁！我突然觉得我这种每次写东西都像日记散文体的人，行文也有逻辑了...
>

是也乎,(￣▽￣)

Markdown 以及更早的 txt2tags/AsciiDoc 等等都称之为

    结构化文本

就是将文章的结构已经含在简洁的字符表述中了的,
一但掌握,自然的撰写时对文章结构也进行了规划.
而且没有增加心灵负担,

善之善也.



-- 
Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by JeremiahZhang** [comment]
雷雨的[Hidden Mission 作业](https://github.com/JeremiahZhang/gopython/blob/master/PY-%E6%98%9F%E9%99%85%E8%BF%B7%E8%88%AA-%E5%A4%87%E6%88%98%E7%AF%87/2015-9-26-HiddenMission-%E5%BC%80%E6%99%BAPy%E5%85%A5%E9%97%A8%E4%BD%93%E9%AA%8C.md)
