### ISSUE TITLE
Ubuntu14.04无法配置无线网卡驱动

### ISSUE THREAD

**Issue by nora614** [OpenMindClub/OMOOC.py#3]
我的ubuntu是用u盘做启动盘装的，在登陆之后总会显示“电脑处于离线状态”

用ifconfig在终端检索，发现wlan0没有显示。在网上搜索后，发现连上宽带可以自己配置无线网卡。可是我的有线也连不上。所以我选择了从win下载文件到ubuntu中装。

最后选择了如下的方法：
- 安装b43-fwcutter, 在光盘/pool/main/b目录下
 然后运行:
- tar xfvj broadcom-wl-4.150.10.5.tar.bz2
   sudo b43-fwcutter -w /lib/firmware wl_apsta-3.130.20.0.o
- sudo b43-fwcutter --unsupported -w /lib/firmware broadcom-wl-4.150.10.5/driver/wl_apsta_mimo.o
- 编辑 /etc/modprobe.d/blacklist.conf 文件, 把其中包含bcm43xx 一行用#注释掉

在此之前下载了这段代码需要的两个程序。唯一和他操作不一样的是第一步没有找到他说的这个目录，就装到home文件夹了。

确保代码无误并且装了多次，发现重启后还是不行。

不知道哪里出了问题。。。

**Comment by ZoomQuiet** [comment]
建议先用 LiveCD 启动一个无误可用 Ubuntu,
看网卡驱动情况,
然后,对应的回来配置

在 2015年3月12日 上午8:28，nora614 <notifications@github.com>写道：

> 我的ubuntu是用u盘做启动盘装的，在登陆之后总会显示“电脑处于离线状态”
>
>
> 用ifconfig在终端检索，发现wlan0没有显示。在网上搜索后，发现连上宽带可以自己配置无线网卡。可是我的有线也连不上。所以我选择了从win下载文件到ubuntu中装。
>
> 最后选择了如下的方法：
>
>    - 安装b43-fwcutter, 在光盘/pool/main/b目录下 然后运行:
>    - tar xfvj broadcom-wl-4.150.10.5.tar.bz2 sudo b43-fwcutter -w
>    /lib/firmware wl_apsta-3.130.20.0.o
>    - sudo b43-fwcutter --unsupported -w /lib/firmware
>    broadcom-wl-4.150.10.5/driver/wl_apsta_mimo.o
>    - 编辑 /etc/modprobe.d/blacklist.conf 文件, 把其中包含bcm43xx 一行用#注释掉
>
> 在此之前下载了这段代码需要的两个程序。唯一和他操作不一样的是第一步没有找到他说的这个目录，就装到home文件夹了。
>
> 确保代码无误并且装了多次，发现重启后还是不行。
>
> 不知道哪里出了问题。。。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenMindClub/OMOOC.py/issues/3>.
>



-- 
Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by nora614** [comment]
我用u 盘做了live cd，然后在开机后进入u 盘点击试用，不知道这样对不对。。。
然后在试用中依旧没有网络连接。

**Comment by YixuanBurnett** [comment]
你试试这个：打开terminal
sudo service network-manager stop
sudo service network-manager start

然后再看看能不能搜索到wifi信号。

**Comment by YixuanBurnett** [comment]
#问题依旧没有被解决，请过路人继续帮忙解决。#
iwconfig 没有wlan0
ifconfig也没有。
尝试激活wlan失败。

猜测：因为用户界面有wifi那个按钮，只是搜索不到网络. 所以应该是有驱动的，
          只是启动失败。可能需要自己安装模块。
如果处理国类似问题，请帮忙解答。

**Comment by leeciyuan** [comment]
大妈，我也是这个问题。
这个是文档的地址：https://help.ubuntu.com/community/WifiDocs/Driver/bcm43xx#b43%20-%20No%20Internet%20access
我选择的是b43 no internet access
然后我已经如第一步所说下载好了fw cutter 第二步的firmware file也下好了，因为我现在是windows和ubuntu双系统（windows能自动连上wifi,ubuntu不能自动连上wifi）,所以我把前面说的那两个文件下载了windows里面。
之后我去ubuntu输入代码：
cd /cdrom/pool/main/b/b43-fwcutter/
sudo dpkg -i b43-fwcutter*
但是显示没有那个文件或目录。
也就是说我第一步就失败了……
我想问的是，windows下载的文件怎么保存到ubuntu 的主文件夹？谢谢！！

**Comment by ZoomQuiet** [comment]
双系统?!
那当然是共享分区了哪,
嘦从 unbuntu 中将 win 的一个分区挂为 /data/win 什么目录上
就好的哪,
当然的, 得是 Ubuntu 能 RW 模式挂的,
要你原先是 NFS 就呵呵了

在 2015年3月12日 下午9:32，leeciyuan <notifications@github.com>写道：

> 大妈，我也是这个问题。
> 这个是文档的地址：
> https://help.ubuntu.com/community/WifiDocs/Driver/bcm43xx#b43%20-%20No%20Internet%20access
> 我选择的是b43 no internet access
> 然后我已经如第一步所说下载好了fw cutter 第二步的firmware
> file也下好了，因为我现在是windows和ubuntu双系统（windows能自动连上wifi,ubuntu不能自动连上wifi）,所以我把前面说的那两个文件下载了windows里面。
> 之后我去ubuntu输入代码：
> cd /cdrom/pool/main/b/b43-fwcutter/
> sudo dpkg -i b43-fwcutter*
> 但是显示没有那个文件或目录。
> 也就是说我第一步就失败了……
> 我想问的是，windows下载的文件怎么保存到ubuntu 的主文件夹？谢谢！！
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenMindClub/OMOOC.py/issues/3#issuecomment-78479352>.
>



-- 
Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by chaonet** [comment]
这个链接里的问题是否跟你的情况一样？[链接](http://forum.ubuntu.org.cn/viewtopic.php?t=466466)
链接里给出了一个Ubuntu的wiki：[链接](https://help.ubuntu.com/community/WifiDocs/Driver/bcm43xx)，可以试试。

**Comment by YixuanBurnett** [comment]
@leeciyuan 已将问题解决。近期将把解决方法po到这上来。
[解决方法及操作步骤(English)](https://help.ubuntu.com/community/WifiDocs/Driver/bcm43xx)

**Comment by leeciyuan** [comment]
解决方法参看文档：https://help.ubuntu.com/community/WifiDocs/Driver/bcm43xx#b43%20-%20No%20Internet%20access
因为我是BCM4312，所以可以选用STA和b43 no Internet access。因为看不懂STA说明。所以用的是B43。
先去launchpad,firmware files把文件下好在windows里面。然后打开ubuntu的主文件夹，左边有一栏有一个设备，下面有好几个盘就对应这win的盘。在里面找到下好的文档。launchpad下载的里面找到fw-cutter，双击会跳到软件中心的界面，点安装。安完以后把firmware files下好的东西复制到主文件夹里面。在第三点里面找到自己的型号下面的代码，在终端执行。运行完就可以直接关掉终端，重启下系统就可以看到wifi了。

**Comment by nora614** [comment]
谢谢各位。今天试了leeciyuan的方法，但是不能用。

然后，然后我发现我的网卡和l的不一样，不能用他的方法。重新查看了wiki之后确定了新方法。

在新方法中，我的所有操作都要围绕这个文件夹“cd /cdrom/pool”展开，但是我的文件夹是空的。我重新插上了自己的U盘启动盘，发现U盘里面是有我需要的东西的。

因为是deb文件，第一次在U盘里直接双击并且把需要的两个文件都安装成功。重启发现不行。第二次我获取了root权限把需要的文件复制到原来的空文件夹当中，并且双击安装和终端都试过了，确定两个文件都显示“安装成功”，重启发现还是不对。ifconfig的结果和原来的一样。很奇怪，明明在软件安装的那里显示成功了，还是没有WiFi

我在找别的方案。。。

**Comment by chaonet** [comment]
@nora614 ，你网卡什么型号？

这是我理解的文档的意思，你可以试着做一遍，如果能成功，就会明白问题出在哪儿了。

需要的文件:

b43-fwcutter

网卡驱动：broadcom-wl-5.100.138.tar.bz2（你之前用的broadcom-wl-4.150.10.5.tar.bz2是ubuntu10.04系统里b43的驱动）

安装步骤：

1. 双击或者在终端安装b43-fwcutter这个工具。文档说的是，可以在安装系统的U盘的/cdrom/pool/main/b/b43-fwcutter/文件夹下找到，也可以直接从网上下载，并没有说一定要有/cdrom/pool/main/b/这个目录。
2. 将网卡驱动复制到主文件夹，打开新的终端窗口，用b43-fwcutter这个工具安装网卡驱动

`tar xfvj broadcom-wl-5.100.138.tar.bz2`

`sudo b43-fwcutter -w /lib/firmware broadcom-wl-5.100.138/linux/wl_apsta.o`

3. 重启电脑
