### ISSUE TITLE
学员github用户名与个人代码仓库清单

### ISSUE THREAD

**Issue by ouyangzhiping** [OpenMindClub/OMOOC.py#6]
请在此处跟帖回复你的Github用户名与个人代码仓库

示范：

* github用户名：ouyangzhiping；
* 个人代码仓库：https://github.com/ouyangzhiping/omooc.py

**Comment by ccqpein** [comment]
ccqpein

On Saturday, March 14, 2015, Zhiping Yang <notifications@github.com> wrote:

> 请在此处跟帖回复你的Github用户名
>
> 示范：
>
>    - ouyangzhiping
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenMindClub/OMOOC.py/issues/6>.
>


-- 
written by ccQ

**Comment by nicetag** [comment]
- github用户名：nicetag；
    - 个人代码仓库：https://github.com/nicetag/omooc.py

```
嗷，是这样吗。。。
```

**Comment by Frank-the-Obscure** [comment]
* GitHub用户名：Frank-the-Obscure；
* 个人代码仓库：https://github.com/Frank-the-Obscure/OMOOC.py

**Comment by balsamleo** [comment]
GitHub用户名：balsamleo;
个人代码仓库：https://github.com/balsamleo/OMOOC.py

**Comment by tonyyet** [comment]
github 用户名：tonyyet
个人代码仓库：https://github.com/tonyyet/omooc.py

**Comment by kidult00** [comment]
GitHub用户名：kidult00
个人代码仓库：https://github.com/kidult00/omooc.py

**Comment by StoneJiaJia** [comment]
Github 用户名：StoneJiaJia
个人代码仓库：https://github.com/StoneJiaJia/omooc.py

**Comment by Rogersunfly** [comment]
github 用户名：rogersunfly
个人代码仓库：https://github.com/Rogersunfly/OMOOC.py

**Comment by tianfrank** [comment]
Github 用户名：tianfrank
个人代码仓库：https://github.com/tianfrank/omooc.py

**Comment by XiangfeiYin** [comment]
Github用户名：XiangfeiYin
个人代码仓库：https://github.com/XiangfeiYin/omooc.py

**Comment by Vesperal-Hunter** [comment]
Github 用户名：Vesperal-Hunter
个人代码仓库：https://github.com/Vesperal-Hunter/omooc.py

**Comment by YixuanBurnett** [comment]
Github用户名：YixuanBurnett
https://github.com/YixuanBurnett/OMOOC.py.git

**Comment by cici1989** [comment]
Github用户名：cici1989;
个人代码仓库：https://github.com/cici1989/omooc.py

**Comment by fengguang22** [comment]
* Github用户名：fengguang22
* 个人代码仓库：https://github/fengguang22/omooc.py

**Comment by fengguang22** [comment]
* Github用户名：fengguang22
* 个人代码仓库：https://github.com/fengguang22/omooc.py

**Comment by ARVn** [comment]
GIthub 用户名：ARVn;
个人代码仓库：https://github.com/ARVn/omooc.py

**Comment by nora614** [comment]
GIthub 用户名：nora614;
个人代码仓库：https://github.com/nora614/omooc.py

**Comment by badboy315** [comment]
GIthub 用户名：badboy315
个人代码仓库：https://github.com/badboy315/omooc.py

**Comment by runbigcat** [comment]
Github 用户名：Runbigcat
个人代码仓库：https://github.com/runbigcat/omooc.py

**Comment by zxcbbn** [comment]
github用户名：zxcbbn；
个人代码仓库：https://github.com/zxcbbn/omooc.py

**Comment by chaonet** [comment]
github用户名：chaonet
个人代码仓库：[https://github.com/chaonet/omooc.py](https://github.com/chaonet/omooc.py)

**Comment by skyworlds** [comment]
github用户名：skyworlds
个人代码仓库：https://github.com/skyworlds/omooc.py.git

**Comment by rosing** [comment]
蝈蝈
github用户名：rosing
个人代码仓库：https://github.com/rosing/omooc.py

**Comment by wdcheng1** [comment]
github用户名：wdcheng1
个人代码仓库:  https://github.com/wdcheng1/omooc.py

**Comment by jiap** [comment]
github用户名：jiap
个人代码仓库：https://github.com/jiap/omooc.py

**Comment by cp4** [comment]
github用户名：cp4 ;
个人代码仓库：https://github.com/cp4/omooc.py

**Comment by csufuyi** [comment]
github用户名：csufuyi
个人代码仓库：https//github.com/csufuyi/omooc.py

**Comment by ouyangzhiping** [comment]
提醒助教：以上已经全部邀请。

**Comment by huhu8** [comment]
github用户名：huhu8
个人代码仓库：https://github.com/huhu8/omooc.py

**Comment by hushaonan** [comment]
github用户名：hushaonan
个人代码仓库: https://github.com/hushaonan/omooc.py

**Comment by mrLuyao** [comment]
github用户名：mrLuyao；
个人代码仓库：https://github.com/mrLuyao/omooc.py

**Comment by sunnydust** [comment]
github用户名：sunnydust
个人代码仓库：https://github.com/sunnydust/omooc.py

**Comment by xiaokechenchen** [comment]
github用户名：xiaokechenchen；
个人代码仓库：https://github.com/xiaokechenchen/omooc.py

**Comment by tornoteli** [comment]
github用户名：tornoteli；
个人代码仓库：https://github.com/tornoteli/omooc.py

**Comment by ashlinglee** [comment]
github用户名：ashlinglee ；
个人代码仓库：https://github.com/ashlinglee/ommc.py

**Comment by ammmn** [comment]
github用户名：ammmn；
个人代码仓库：https://github.com/ammmn/omooc.py

**Comment by yzha3917** [comment]
github用户名：yzha3917；
个人代码仓库：https://github.com/yzha3917/omooc.py

**Comment by baibanbao** [comment]
github用户名：baibanbao
个人代码大仓库：https://github.com/baibanbao/omooc.py

**Comment by clamclair** [comment]
github用户名：  clamclair
个人代码仓库：https://github.com/clamclair/omccy.py.git

**Comment by Wenzy--** [comment]
github用户名：wenzy--
个人代码仓库：https://github.com/Wenzy--/omooc.py

**Comment by leokaikai** [comment]
github用户名：leokaikai
个人代码仓库：https://github.com/leokaikai/OMOOC.py

**Comment by ouyangzhiping** [comment]
提醒助教：以上已经全部邀请。

**Comment by xiaomai2015** [comment]
github用户名：xiaomai2015
个人代码仓库：https://github.com/xiaomai2015/omooc.py

**Comment by ouyangzhiping** [comment]
提醒助教：以上已经全部邀请。

**Comment by Lillianmin** [comment]
github用户名：Lillianmin；
个人代码仓库：https://github.com/Lillianmin/omooc.py

**Comment by leeciyuan** [comment]
github用户名：leeciyuan；
个人代码仓库：https://github.com/leeciyuan/omooc.py

**Comment by 42wolf** [comment]
github用户名：42wolf
个人代码仓库：https://github.com/42wolf/omooc.py

**Comment by ziyanziyan** [comment]
github用户名：ziyanziyan
个人代码仓库：https://github.com/ziyanziyan/omooc.py

**Comment by ruoweifly** [comment]
github用户名：ruoweifly；
个人代码仓库：https://github.com/ruoweifly/omooc.py

**Comment by sanyue3always** [comment]
github用户名：sanyue3always
个人代码仓库: https://github.com/sanyue3always/omooc.py

**Comment by ouyangzhiping** [comment]
提醒助教：以上已经全部邀请。

**Comment by yangtzehina** [comment]
用户名：yangtzehina
个人代码仓库：https://github.com/yangtzehina/omooc.py

**Comment by duanxinxing** [comment]
用户名：duanxinxing
个人代码仓库：https://github.com/duanxinxing/omooc.py

**Comment by ouyangzhiping** [comment]
提醒助教：以上已经全部邀请。

**Comment by allansmith2009** [comment]
github用户名：allansmith2009； 
个人代码仓库：https://github.com/allansmith2009/omooc.py

**Comment by sunmmy** [comment]
github用户名：sunmmy
个人代码仓库：https://github.com/sunmmy/omooc.py

**Comment by phoebeyeah** [comment]
github用户名：phoebeyeah
个人代码仓库：https://github.com/phoebeyeah/omooc.py

**Comment by Rainvoo** [comment]
GIthub 用户名：Rainvoo
个人代码仓库：https://github.com/Rainvoo/omooc.py.git

**Comment by xiulizhuang** [comment]
GIthub 用户名：xiulizhuang
个人代码仓库：https://github.com/xiulizhuang/OMOOC.py

**Comment by xyviva** [comment]
GitHub的用户名：xyviva
个人代码仓库：https://github.com/xyviva/omooc.py

**Comment by dudutang** [comment]
GitHub的用户名：dudutang
个人代码仓库：https://github.com/dudutang/omooc.py

**Comment by umulily** [comment]
吴祖利
GitHub的用户名：umulily
个人代码仓库：https://github.com/umulily/omooc.py

**Comment by zsisi** [comment]
GitHub的用户名：zsisi
个人代码仓库：https://github.com/zsisi/omooc.py

**Comment by ouyangzhiping** [comment]
提醒助教：以上已经全部邀请。

**Comment by wangyujie123** [comment]
GitHub的用户名：wangyujie123
个人代码仓库：https://github.com/wangyujie123/OMOOC.py

**Comment by xiaojingli** [comment]
github用户名：xiaojingli
个人代码仓库：https://github.com/xiaojingli/omooc.py

**Comment by ouyangzhiping** [comment]
提醒助教：以上已经全部邀请。

**Comment by ouyangzhiping** [comment]
![Uploading Screenshot 2015-03-16 09.18.43.png . . .]()

![Uploading Screenshot 2015-03-16 09.19.02(2).png . . .]()


请以上学员确认邀请。

**Comment by ouyangzhiping** [comment]
请以上学员确认邀请。

**Comment by ouyangzhiping** [comment]
请学员确认邀请。

**Comment by reinhartzzhang** [comment]
github用户名：reinhartzzhang
个人代码仓库：https://github.com/reinhartzzhang/omooc.py.git

**Comment by zshaolin** [comment]
github用户名：zshaolin
个人代码仓库：https://github.com/zshaolin/omooc.py.git

**Comment by ouyangzhiping** [comment]
提醒助教：以上已经全部邀请。

**Comment by helenysli** [comment]
github用户名：helenysli
个人代码仓库：https://github.com/helenysli/omooc.py

**Comment by ccqpein** [comment]
已添加

2015-03-23 21:50 GMT+08:00 helenysli <notifications@github.com>:

> github用户名：helenysli
> 个人代码仓库：https://github.com/helenysli/omooc.py
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenMindClub/OMOOC.py/issues/6#issuecomment-85003796>.
>



-- 
written by ccQ

**Comment by ZoomQuiet** [comment]
for 1.OMOOC.py
