### ISSUE TITLE
如何在 markdown 语法下键入换行符(How to Newline in Markdown? )

### ISSUE THREAD

**Issue by fengdasuk19** [OpenMindClub/OMOOC.py#9]
# 如何在 markdown 语法下键入换行符(How to Newline in Markdown? )

## 标准 Markdown (Standard Markdown, SM) 版 ##

对于用惯 `Microsoft Word` 的人来说需要注意一点：写作者必须键入**2个连续的**`空格`之后再键入 1 个换行符（`Enter` * 1），才能完成`强制换行`这个动作（参考[[1]](https://github.com/typecho/typecho/issues/51)与[[2]](http://wowubuntu.com/markdown/#p)）。

也就是说，为了在 SM 中得到如下显示：
Or you won't succed, 
only to get a long line like this sentence.

应键入以下代码：（1 个 [Space] 代表 1 个空格字符）
`Or you won't succed, `**`[Space][Space]`**
`only to get a long line like this sentence.`

否则，当你键入以下代码时：
`Or you won't succed, `
`only to get a long line like this sentence.`

你将得到如下显示：
Or you won't succed, only to get a long line like this sentence.

类似地，通过 2 个连续的换行符（`Enter` * 2）可达到强制换段的目的。

Users who are used to typing in `Microsoft Word` need to notice this: to create a newline, you need to type **TWO CONSECUTIVE** `Space` before you type `Enter`, or to type a `Enter` followed by another new one.  

Namely, to get stuff like the following:
Or you won't succed, 
only to get a long line like this sentence.

you need to type code like this:( each [Space] means one space character)
`Or you won't succed, `**`[Space][Space]`**
`only to get a long line like this sentence.`

Or when you type code like this:
`Or you won't succed, `
`only to get a long line like this sentence.`

you'll get the following:
Or you won't succed, only to get a long line like this sentence.

Similarly, you can type two **TWO CONSECUTIVE** `Enter` to get a new paragraph.

## [GitHub Flavored Markdown(GFM)](https://help.github.com/articles/github-flavored-markdown/) 版 ##

经 [yzha3917](https://github.com/yzha3917) 的[提醒](https://github.com/OpenMindClub/OMOOC.py/issues/10#issuecomment-81923507)，我在 [《Writing on GitHub》](https://help.github.com/articles/writing-on-github/) 中发现了这个：

> Issues, comments, and pull request descriptions are written using GitHub Flavored Markdown along with some additional features to make writing content on GitHub easy.

也就是说在 **Issues**、**Comments**、**pull request descriptions** 这 3 部分采用了 GitHub 方言（GFM）处理，在这些地方写作而需要换行时，仅需像在 `Mircrosoft Word` 等传统 MS 文本处理软件中一样，键入 1 个换行符（`Enter` * 1）即可。

例如，还是上面那个例子，当在 GitHub 的上述 3 个地方书写时，仅需按照上面本在 SM 中失效的代码，即
`Or you won't succed, `
`only to get a long line like this sentence. `

即可得到下面的效果：
Or you won't succed, 
only to get a long line like this sentence. 

## 参考资料  
1. [添加 markdown 回车换行语法 #51](https://github.com/typecho/typecho/issues/51)
2. [Markdown 语法说明 (简体中文版) ：段落和换行](http://wowubuntu.com/markdown/#p)
3. [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/)
4. [Writing on GitHub](https://help.github.com/articles/writing-on-github/)
5. [Writing on GitHub - Newlines](https://help.github.com/articles/writing-on-github/#newlines)

**Comment by tonyyet** [comment]
初学者假如想比较容易记住什么标记符号对应什么样的效果的话，可以考虑使用一些支持预览功能的文本编辑器。

假如是用 Mac OSX 操作系统的话，可以考虑用 [Mou](http://25.io/mou/) 或者 [MacDown](http://macdown.uranusjr.com/) 来编辑 markdown 文本，这两个文本编辑器都支持实时预览markdown被render成html的效果。

假如用Win系统的话可以用 [MarkdownPad](http://www.markdownpad.com/)。

假如用Ubuntu 的话，可以考虑 [ReText](http://blog.sudobits.com/2012/10/12/markdown-editor-for-ubuntu-12-0412-10/)。

**Comment by fengdasuk19** [comment]
请注意：Markdown 有多种方言，这是指同样的代码在不同环境下解释不一致。


因此，将代码从一种环境迁移到另一种环境中时，请小心核对：如在 [MarkdownPad 2](http://www.markdownpad.com/) 下的实现和在 GitHub 上的实现不一定一致，例子请参见[《Markdown 列表FAQ(FAQ about Markdown List)》](https://github.com/OpenMindClub/OMOOC.py/issues/10)。

**Comment by fengdasuk19** [comment]
刚刚发现：造成显示差异的似乎是 GitHub 的 Code 与 Issues 的实现方式差异，而非 GitHub 与 MarkdownPad 2 的实现方式差异。

有兴趣的可对比[《Markdown 列表FAQ(FAQ about Markdown List)》](https://github.com/OpenMindClub/OMOOC.py/issues/10)的[代码](https://github.com/fengdasuk19/omooc.py/blob/master/Markdown/tmp-code-ompy-issue-10.md) 与 我这份[打算放进书的md文件](https://github.com/fengdasuk19/pythoncamp0/blob/master/source/Markdown/FAQ/faq-markdown-list.md)的代码之间的差异。

**Comment by ziyanziyan** [comment]
在 Github Wiki 中使用 <br/> 可行。

可以测试：
段尾加上两个或以上空格
/ 连续回车两次
/ 使用 HTML 换行符 <br/>

http://www.zhihu.com/question/20134106
